# Generated by Django 6.1 on 2026-08-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('fr', 'Français'), ('ar', 'Arabe')], default='fr', max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super administrateur'), ('GYM_OWNER', 'Propriétaire'), ('MANAGER', 'Responsable'), ('RECEPTIONIST', 'Réceptionniste'), ('COACH', 'Coach'), ('MEMBER', 'Adhérent')], default='MEMBER', max_length=20),
        ),
    ]
