# Generated by Django 6.1 on 2026-08-11 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_phone_user_preferred_language_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super-administrateur'), ('COORDINATOR', 'Coordinateur'), ('MEMBER', 'Adhérent')], default='MEMBER', max_length=20),
        ),
    ]
