# Generated by Django 6.1 on 2026-08-08 21:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom de la salle')),
                ('slug', models.SlugField(help_text='Exemple : atlas-fitness', max_length=160, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='gyms/logos/')),
                ('primary_color', models.CharField(default='#2563EB', max_length=7, validators=[django.core.validators.RegexValidator(message='Utilisez une couleur au format #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('secondary_color', models.CharField(default='#111827', max_length=7, validators=[django.core.validators.RegexValidator(message='Utilisez une couleur au format #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('language', models.CharField(choices=[('fr', 'Français'), ('ar', 'Arabe')], default='fr', max_length=2)),
                ('currency', models.CharField(default='MAD', max_length=3)),
                ('status', models.CharField(choices=[('TRIAL', 'Période d’essai'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspendue'), ('CANCELLED', 'Annulée')], default='TRIAL', max_length=15)),
                ('trial_ends_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(limit_choices_to={'role': 'GYM_OWNER'}, on_delete=django.db.models.deletion.PROTECT, related_name='owned_gyms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salle',
                'verbose_name_plural': 'Salles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom de l’établissement')),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_main', models.BooleanField(default=False, verbose_name='Établissement principal')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='gyms.gym')),
            ],
            options={
                'verbose_name': 'Établissement',
                'verbose_name_plural': 'Établissements',
                'ordering': ['gym', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GymUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Propriétaire'), ('MANAGER', 'Responsable'), ('RECEPTIONIST', 'Réceptionniste'), ('COACH', 'Coach')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='gyms.branch')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='gyms.gym')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employé de salle',
                'verbose_name_plural': 'Employés des salles',
                'ordering': ['gym', 'user'],
            },
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('gym', 'name'), name='unique_branch_name_per_gym'),
        ),
        migrations.AddConstraint(
            model_name='gymuser',
            constraint=models.UniqueConstraint(fields=('gym', 'user'), name='unique_user_per_gym'),
        ),
    ]
