# Generated by Django 6.1 on 2026-08-11 21:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='branch',
            name='unique_branch_name_per_gym',
        ),
        migrations.RemoveConstraint(
            model_name='gymuser',
            name='unique_user_per_gym',
        ),
        migrations.AlterModelOptions(
            name='gym',
            options={'verbose_name': 'Salle', 'verbose_name_plural': 'Salle'},
        ),
        migrations.RemoveField(
            model_name='gym',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='gym',
            name='language',
        ),
        migrations.RemoveField(
            model_name='gym',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='gym',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='gym',
            name='status',
        ),
        migrations.RemoveField(
            model_name='gym',
            name='trial_ends_at',
        ),
        migrations.AddField(
            model_name='gym',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gym',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='gym',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Salle active'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='gym/logo/'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='primary_color',
            field=models.CharField(default='#2563EB', max_length=7, validators=[django.core.validators.RegexValidator(message='Utilisez une couleur au format #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Couleur principale'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='secondary_color',
            field=models.CharField(default='#111827', max_length=7, validators=[django.core.validators.RegexValidator(message='Utilisez une couleur au format #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Couleur secondaire'),
        ),
        migrations.RemoveField(
            model_name='gymuser',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='gymuser',
            name='gym',
        ),
        migrations.RemoveField(
            model_name='gymuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='GymUser',
        ),
    ]
